In [1]:
import numpy as np

In [2]:
a=np.array([[0,1],[2,3]])

In [3]:
a

array([[0, 1],
       [2, 3]])

In [4]:
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [5]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [6]:
np.resize(a,(2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])